#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json

from flask import Flask
from flask import render_template
from flask import request
from multiprocessing import Process
from copy import deepcopy

app = Flask(__name__)

RQ = None
WQ = None

WQ_DICT = {'from': 'server'}

@app.route('/')
def index():
    WQ.put('get index.html')
    return render_template('index.html')


@app.route('/task', methods=['POST'])
def add_task():
    wqd = deepcopy(WQ_DICT)
    wqd['command'] = 'create'
    wqd['param'] = {'url': request.form['url']}
    wqd['ydl_opts'] = {}

    WQ.put(sqd)
    ret = RQ.get()
    return json.dumps(ret)


@app.route('/task/list', methods=['GET'])
def list_task():
    pass


@app.route('/task/state_counter', methods=['GET'])
def list_state():
    pass


@app.route('/task/tid/<tid>', methods=['DELETE'])
def delete_task(tid):
    WQ.put({'



class Server(Process):
    def __init__(self, rqueue, wqueue):
        super(Server, self).__init__()
        self.rq = rqueue
        self.wq = wqueue

        global RQ
        global WQ
        RQ = rqueue
        WQ = wqueue

    def run(self):
        app.run(use_reloader=False)


